version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: clinic-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clinic
      # (Optional) create additional user:
      # MYSQL_USER: clinic
      # MYSQL_PASSWORD: clinicpass
    ports:
      - "3306:3306" # change left side to 3307 if 3306 is taken
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: ["--default-authentication-plugin=caching_sha2_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

volumes:
  mysql_data:
    driver: local

# Usage:
# 1. docker compose up -d db
# 2. (First run waits while MySQL initializes ~10-20s.)
# 3. Backend .env DB_* values should match the above (DB_USER=root, DB_PASS=password, DB_NAME=clinic, DB_HOST=localhost, DB_PORT=3306)
# 4. Run backend with: npm run start:dev (inside backend folder).
# If port 3306 was busy and you changed it to 3307 on the left side, set DB_PORT=3307 in backend .env.
